# Stock Market Analytics Dashboard

## Notebook 2: Understanding the Dataset

### Objective

This notebook explores the historical stock market data collected from Yahoo Finance.

The goal is to understand the dataset before performing any cleaning or financial analysis.

In [9]:
import pandas as pd
import matplotlib.pyplot as plt

pd.set_option("display.max_columns", None)

In [10]:
df = pd.read_csv("../data/processed/master_stock_data.csv")

df.head()

,Date,Adj Close,Close,High,Low,Open,Volume,Ticker
0,2020-01-02,72.333878,75.087502,75.150002,73.797501,74.059998,135480400,AAPL
1,2020-01-03,71.630661,74.357498,75.144997,74.125000,74.287498,146322800,AAPL
2,2020-01-06,72.201416,74.949997,74.989998,73.187500,73.447502,118387200,AAPL
3,2020-01-07,71.861855,74.597504,75.224998,74.370003,74.959999,108872000,AAPL
4,2020-01-08,73.017845,75.797501,76.110001,74.290001,74.290001,132079200,AAPL

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6290 entries, 0 to 6289
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       6290 non-null   str
 1   Adj Close  6290 non-null   float64
 2   Close      6290 non-null   float64
 3   High       6290 non-null   float64
 4   Low        6290 non-null   float64
 5   Open       6290 non-null   float64
 6   Volume     6290 non-null   int64
 7   Ticker     6290 non-null   str
dtypes: float64(5), int64(1), str(2)
memory usage: 393.3 KB

In [12]:
df.shape

(6290, 8)

In [13]:
df.columns

Index(['Date', 'Adj Close', 'Close', 'High', 'Low', 'Open', 'Volume',
       'Ticker'],
      dtype='str')

In [14]:
df.describe()

,Adj Close,Close,High,Low,Open,Volume
count,6290.000000,6290.000000,6290.000000,6290.000000,6290.000000,6.290000e+03
mean,148.054515,150.541544,152.188571,148.772205,150.486956,1.335117e+08
std,93.522212,95.856497,96.588966,95.044535,95.854300,1.815927e+08
min,4.885130,4.910000,5.248500,4.517000,5.002500,7.164500e+06
25%,91.879398,92.422499,93.963749,90.855000,92.474001,3.008338e+07
50%,139.895920,141.529999,143.254997,139.764999,141.559998,5.415195e+07
75%,182.509521,184.224998,185.882248,182.474998,184.152500,1.223203e+08
max,460.325623,467.559998,468.350006,464.459991,467.000000,1.543911e+09

In [15]:
df.isnull().sum()

Date         0
Adj Close    0
Close        0
High         0
Low          0
Open         0
Volume       0
Ticker       0
dtype: int64

In [16]:
df.duplicated().sum()

np.int64(0)

In [17]:
df["Ticker"].unique()

<StringArray>
['AAPL', 'MSFT', 'NVDA', 'AMZN', 'GOOGL']
Length: 5, dtype: str

In [18]:
df["Ticker"].nunique()

5